# 01 - Summarise generated spatial object

#' Summarise a generated riskGenerateR spatial object
#'
#' Provides a compact quality-assurance and descriptive summary of an
#' `sf` object used or generated by riskGenerateR.
#'
#' The summary reports object dimensions, geometry and CRS information,
#' geometry validity, bounding box information, and summaries of selected
#' attributes generated by riskGenerateR when present.
#'
#' `rgr_summary()` does not calculate risk metrics, rates, expected counts,
#' priorities, or other analytical outputs.
#'
#' Area values are reported using the units represented by the object's
#' existing `area` field. No unit conversion is performed.
#'
#' @param x An sf object.
#'
#' @return An object of class `rgr_summary`.
#'
#' @export
rgr_summary <- function(x) {

  # 01 - Validate input -----------------------------------------------------

  if (!requireNamespace("sf", quietly = TRUE)) {
    stop(
      "Package 'sf' is required.",
      call. = FALSE
    )
  }

  if (!inherits(x, "sf")) {
    stop(
      "x must be an sf object.",
      call. = FALSE
    )
  }


  # 02 - Spatial metadata ---------------------------------------------------

  geometry_types <- unique(
    as.character(
      sf::st_geometry_type(x)
    )
  )

  crs <- sf::st_crs(x)

  geometry_valid <- sf::st_is_valid(x)
  geometry_empty <- sf::st_is_empty(x)


  # 03 - Core QA summary ----------------------------------------------------

  out <- list(
    rows = nrow(x),
    columns = ncol(x),
    geometry_types = geometry_types,
    crs_epsg = crs$epsg,
    crs_name = crs$Name,
    valid_count = sum(
      geometry_valid,
      na.rm = TRUE
    ),
    invalid_count = sum(
      geometry_valid %in% FALSE,
      na.rm = TRUE
    ),
    empty_count = sum(
      geometry_empty,
      na.rm = TRUE
    ),
    bbox = sf::st_bbox(x)
  )


  # 04 - Attribute-generation metadata -------------------------------------

  if ("rgr_attribute_type" %in% names(x)) {
    out$attribute_type_count <- table(
      x[["rgr_attribute_type"]],
      useNA = "ifany"
    )
  }


  # 05 - Incident count attributes -----------------------------------------

  if ("event_count" %in% names(x)) {
    out$total_event_count <- sum(
      x[["event_count"]],
      na.rm = TRUE
    )

    out$event_count_summary <- summary(
      x[["event_count"]]
    )
  }


  # 06 - Generic count attributes ------------------------------------------

  if ("count" %in% names(x)) {
    out$total_count <- sum(
      x[["count"]],
      na.rm = TRUE
    )

    out$count_summary <- summary(
      x[["count"]]
    )
  }


  # 07 - Area attributes ----------------------------------------------------

  if ("area" %in% names(x)) {
    out$total_area <- sum(
      x[["area"]],
      na.rm = TRUE
    )

    out$area_summary <- summary(
      x[["area"]]
    )
  }


  # 08 - Selected contextual attributes ------------------------------------

  if ("hazard_category" %in% names(x)) {
    out$hazard_category_count <- table(
      x[["hazard_category"]],
      useNA = "ifany"
    )
  }

  if ("event_type" %in% names(x)) {
    out$event_type_count <- table(
      x[["event_type"]],
      useNA = "ifany"
    )
  }

  if ("observation_type" %in% names(x)) {
    out$observation_type_count <- table(
      x[["observation_type"]],
      useNA = "ifany"
    )
  }

  if ("risk_category" %in% names(x)) {
    out$risk_category_count <- table(
      x[["risk_category"]],
      useNA = "ifany"
    )
  }

  if ("category" %in% names(x)) {
    out$category_count <- table(
      x[["category"]],
      useNA = "ifany"
    )
  }


  # 09 - Class and return ---------------------------------------------------

  class(out) <- c(
    "rgr_summary",
    class(out)
  )

  out
}
